name: lint

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
    - name: Lint
      run: |
        npm install
        npm run lint
    - name: Commit formatted code
      if: github.repository_owner == 'CuteReimu'
      run: |
        if [[ -n $(git status --porcelain) ]]; then
        git config --local user.name 'github-actions[bot]'
        git config --local user.email '41898282+github-actions[bot]@users.noreply.github.com'
        git add --all
        git commit -m "gradlew ktlintFormat"
        else
        echo "No changes to the output on this push; exiting."
        fi
    - name: Push changes
      uses: ad-m/github-push-action@master
      if: github.repository_owner == 'CuteReimu'
      continue-on-error: true
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
